server:
  error:
    include-stacktrace: on_param

spring:
  datasource:
#    url: jdbc:mysql://localhost:52000/anime?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    url: jdbc:mysql://localhost:52000/anime?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

